#!/bin/bash
if [ ! -f "/etc/profile.d/etrobo.sh" ]; then
    export ETROBO_ROOT="$(cd `dirname $0`; pwd)/etrobo"
    tmpFile=$(mktemp)
    echo "export ETROBO_ROOT=\"$ETROBO_ROOT\"" > tmpFile
    echo "source \"$ETROBO_ROOT/scripts/etroboenv.sh\"" >> tmpFile
    sudo mv tmpFile /etc/profile.d/etrobo.sh
fi
if [ ! -d "$ETROBO_ROOT" ]; then
    sudo apt -y update
    sudo apt -y upgrade
    sudo apt -y install build-essential
    sudo apt -y install git
    sudo apt -y install ruby

    cd "`dirname $0`"
    git clone https://github.com/ETrobocon/etrobo.git
    "$ETROBO_ROOT/scripts/setup.sh"
fi
code "$ETROBO_ROOT"
